### ISSUE TITLE
PlotScatter offset argument not acting

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#114]
As for https://github.com/epezent/implot/tree/c0409ff4ffde00e19203bb4537676f2b079805f3

PlotScatter offset argument is behaving as always 0.

```Lua
ig.SliderInt("Offset", offset, 0, #Poly+1);
...
ig.ImPlot_PlotScatter("vertex", xs1, ys1, 1, offset[0]);
```

But here is working

```Lua
ig.SliderInt("Offset", offset, 0, #Poly+1);
...
ig.ImPlot_PlotScatter("vertex", xs1 + offset[0], ys1 + offset[0], 1);
```

**Comment by epezent** [comment]
By design, the offset is modulo'd by the count internally. So because your count is 1, the offset will always be zero. 

What you're trying to do isn't really what `offset` was designed for. Offset is meant to enable traversing circular buffers. If you only want to index one particular value of a buffer, then your second approach is more appropriate. 

I should probably document offset a little better to be fair.
