### ISSUE TITLE
time series plot 

### ISSUE THREAD

**Issue by yukinjie** [epezent/implot#156]
candlestick chart plot issues:
how to delete blank date (weekend or holiday) in time series drawing?
![demo](https://user-images.githubusercontent.com/12825801/101243449-732f2600-373b-11eb-96d2-86b4600cf445.png)

**Comment by epezent** [comment]
It's not currently possible to remove the weekends. I don't foresee it being supported unless someone other than me is willing to make major edits to how time axes are handled. Sorry.

**Comment by yukinjie** [comment]
thank you!

**Comment by leeoniya** [comment]
@epezent this is actually not that difficult to do, but you have to treat the x scale as ordinal. this means you give up logical temporal tick values, since the scale becomes unpredictble/discontinuous. so basically just pull every 10th x value or whatever and format that as time for the tick value.

that's what i do here: https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html
