### ISSUE TITLE
Keeping max y values inside plot rectangle when zooming in and changing only x axis min-max 

### ISSUE THREAD

**Issue by G-Alevizos** [epezent/implot#192]
First of all, great work with this library, it has helped me a lot during the past few days.

My issue is that I am trying to simulate the behaviour below
![sample](https://user-images.githubusercontent.com/23016416/111775869-f8d57c80-88b9-11eb-8de8-10c8c9853ce6.gif)
in which the y axis is limited to the maximum y value of the input data and the x axis gets resized when zooming in.

I haven't really found a way to replicate this with ImPlot and after a look at the code, I hypothesize it has something to do with setting the max-min y value of the plot rectangle with the local input data max-min and resizing the x-axis accordingly based on the `zoom_rate`.

I have also tried the `ImPlotFlags_Equal` flag but it is not suited to my case.

Thanks in advance!

**Comment by G-Alevizos** [comment]
After locking the y_axis from `ImPlot::SetNextPlotLimitsY` there seems to be some progress though. I need that exact behaviour for the plotted area when zooming.

**Comment by epezent** [comment]
@G-Alevizos , judging from the GIF you provided, it seems that the y-axis is constrained to fit to the _visible_ data in the plot window, not the entire input data (i.e. y-values that are outside the plot area are not taken into consideration for the fit). Is that what you are trying to achieve, or did you actually mean all y-points? If it's the latter, then I think you should be able to acheive this with:

```cpp
// Fits the next plot axes to all plotted data if they are unlocked (equivalent to double-clicks).
void FitNextPlotAxes(bool x = true, bool y = true, bool y2 = true, bool y3 = true);
```

Setting x to false, y to true, and ignoring the additional y-axes. Let me know how close that gets you to your desired behavior. If you actually only want to fit the _visible_ data, this may require some tinkering on our end. Let me know.

Glad the library has been helpful otherwise!

**Comment by epezent** [comment]
Alternatively, you can try enabling `ImPlotAxisFlags_AutoFit` for your y-axis only.

**Comment by G-Alevizos** [comment]
Hello, @epezent, and thanks for the reply!

Since constraining the y-axis to fit the visible plot data was my initial goal, enabling the `ImPlotAxisFlags_AutoFit` flag for the y-axis seems to work like a charm so far, with the only issue being that the y-axis ticks don't get adjusted to the visible data but keep their initial values, which is not really a problem right now.

**Comment by epezent** [comment]
@G-Alevizos , see #200. Please close the issue if `ImPlotAxisFlags_AutoFit|ImPlotAxisFlags_RangeFit` meets your needs. Thanks!

**Comment by G-Alevizos** [comment]
Hello again @epezent,
Just tried the suggested combination of flags after pulling the latest commit and it works exactly as expected. Thank you very much for this addition! Closing this issue as it has been resolved.
