### ISSUE TITLE
Division by 0 in UpdateTransformCache

### ISSUE THREAD

**Issue by Lectem** [epezent/implot#229]
In the case where the minimum for an axis is 0, it causes a division by 0 here (and for Y axes):
https://github.com/epezent/implot/blob/555ff688a8134bc0c602123149abe9c17d577475/implot.cpp#L514

This can be an issue when float exceptions are enabled.
I fixed this by arbitrarily setting `LogDenX` to `0` if the min value is 0, however I am unsure if you would want to fix it another way.
Note that it also causes issues if the Max/Min value is negative.

**Comment by epezent** [comment]
This shouldn't matter since we always constrain the min value to be above 0 when log scale is enabled _before_ `UpdateTransformCache` is ever called. However, we always calculate LogDen even if log scale is not enable, which is why you are seeing the exception. I've added a conditional that will skip the calculation of log scale is not enabled:

https://github.com/epezent/implot/commit/e9469cf347445f406fba07859a45337818bdfabb

**Comment by Lectem** [comment]
It's less about the fact it could be incorrect and more about having to wrap code with disabled float exceptions :)

Thanks!
