### ISSUE TITLE
Is there a way to remove the margin around a plot?

### ISSUE THREAD

**Issue by perrymacmurray** [epezent/implot#258]
Hi everyone,
I'm currently designing a GUI with ImPlot for viewing different variables in a program. There are going to be quite a few smaller plots, so I've been trying to save as much space as possible. I noticed though that even after removing decorations and setting PlotPadding to (0, 0), there seems to be a margin around the outside of a plot I can't get rid of:
![image](https://user-images.githubusercontent.com/20259300/123142776-6942eb00-d41f-11eb-888c-960b18d9d6a5.png)
_(It's difficult to see the white-on-gray margin around it, so hopefully the red lines help)_

Is it possible to further reduce/remove these margins? I've already tried the PlotPadding, LabelPadding, and FitPadding style vars, and have also tried setting the CanvasOnly ImPlotFlag.

Here's my relevant code (although I am using Java bindings so it isn't 1:1 with what a C++ implementation would be):
```java
int graphWidth = 500;
int graphHeight = 65;
ImPlot.pushStyleVar(ImPlotStyleVar.PlotPadding, new ImVec2(0, 0));
ImPlot.pushStyleVar(ImPlotStyleVar.LabelPadding, new ImVec2(0, 0));
ImPlot.pushStyleVar(ImPlotStyleVar.LegendPadding, new ImVec2(0, 0));
ImPlot.pushStyleVar(ImPlotStyleVar.FitPadding, new ImVec2(0, 0));
if (ImPlot.beginPlot("##" + variable.getName() + "Plot", "", "", new ImVec2(graphWidth, graphHeight), ImPlotFlags.NoMenus | ImPlotFlags.NoBoxSelect, ImPlotAxisFlags.NoDecorations | ImPlotAxisFlags.AutoFit, ImPlotAxisFlags.NoGridLines | ImPlotAxisFlags.NoTickMarks | ImPlotAxisFlags.NoTickLabels | ImPlotAxisFlags.AutoFit))
{
    Double[] data = ImPlotTools.removeNullElements(values);
    ImPlot.plotLine(variable.getName(), ImPlotTools.createIndex(data), data);
    ImPlot.endPlot();
}
ImPlot.popStyleVar(4);
```

**Comment by epezent** [comment]
Here how the code you provided works for me:

w/o Push:

```cpp
ImGui::Begin("Test");
if (ImPlot::BeginPlot("##Test","","",,ImVec2(500,65),ImPlotFlags_NoMenus | ImPlotFlags_NoBoxSelect, ImPlotAxisFlags_NoDecorations | ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_AutoFit)) {
    ImPlot::EndPlot();
}
ImGui::End();
```

![image](https://user-images.githubusercontent.com/29577475/123188161-6c0a0400-d450-11eb-99d2-7e2cbf843ceb.png)

w/ Push

```cpp
ImGui::Begin("Test");
ImPlot::PushStyleVar(ImPlotStyleVar_PlotPadding, ImVec2(0,0));
if (ImPlot::BeginPlot("##Test","","",,ImVec2(500,65),ImPlotFlags_NoMenus | ImPlotFlags_NoBoxSelect, ImPlotAxisFlags_NoDecorations | ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_AutoFit)) {
    ImPlot::EndPlot();
}
ImPlot::PopStyleVar();
ImGui::End();
```

![image](https://user-images.githubusercontent.com/29577475/123188097-467cfa80-d450-11eb-9e54-af65bf378b62.png)

As you can see, `ImPlotStyleVar_PlotPadding` eliminates the frame (blue) padding for me, except for the left side. That is because you have passed `""` for the y-label which will still result in padding equivalent to text line height being added. If you want to eliminate this, either pass NULL or 0 for the y-label, or add `ImPlotAxisFlags_NoLabel`. So, why didn't the x-label display the same behavior? Because you passed `ImPlotAxisFlags_NoDecorations` for it, which includes `ImPlotAxisFlags_NoLabel`.

I think what you want is this:

```cpp
ImPlot::PushStyleVar(ImPlotStyleVar_PlotPadding, ImVec2(0,0));
if (ImPlot::BeginPlot("##Plot",0,0,ImVec2(500,65),ImPlotFlags_NoMenus | ImPlotFlags_NoBoxSelect, ImPlotAxisFlags_NoDecorations | ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_AutoFit)) {
    
    ImPlot::EndPlot();
}
ImPlot::PopStyleVar();
```

![image](https://user-images.githubusercontent.com/29577475/123188809-85f81680-d451-11eb-9fde-6d94858ca792.png)


Though this doesn't explain why you still see white margins in your image. I suggest checking your wrapper implementation. As you can see above, it should work.

**Comment by perrymacmurray** [comment]
Thanks so much for your help! After some testing with your code, the problem definitely exists within the Java wrapper.
