### ISSUE TITLE
ImPlot namespace and style

### ISSUE THREAD

**Issue by ocornut** [epezent/implot#29]
Congratulations on the amazing library! (I noticed it was linked from Hackernews and Reddit recently, hence possibly influx of users)

As discussed earlier, I feel like using a distinct namespace e.g. `ImPlot` may be easier for users to find/distinguish among functions provided by this library (because it has many functions).

If anything we could imagine that large features of ImGui with many entry points could want adopt the same idea but there are none so far (Tables API being the closest and many of its function are prefixed ImGui::TableXXX for that reason).

**Comment by epezent** [comment]
Yes, I think your tweet might have started all that! We appreciate the exposure!

Regarding the namespace, yes, it's still going to happen. We had a few lingering PRs that I wanted to merge first (namely @jpieper's multi-axis work).

I was already sort-of doing what you are with Tables -- prefixing functions with `PlotXXX`. If I am to change the namespace, then that becomes unnecessary so I will also likely shorten a few function names while I'm at it. 

Best to get this over with now, so expect the change soon (probably this evening).

**Comment by epezent** [comment]
Per @ocornut's suggestion and previous discussions, the `ImPlot` namespace has been adopted. As a result, two additional changes were made:

- Some functions that were prefixed or decorated with the word "Plot" have been truncated. E.g., `ImGui::PlotBar` is now just `ImPlot::Bar`. I didn't change everything, however, e.g., `BeginPlot` is still `BeginPlot` (rational being that someday we may have `BeginFlameGraph`, or some other context that doesn't work make sense on conventional cartesian axes.)
- Some functions have been given names that would have otherwise collided with the ImGui namespace. This has been done to maintain a consistent style with ImGui. E.g., 'ImGui::PushPlotStyleVar` is now 'ImPlot::PushStyleVar`. Yes, it does make it a bit easier to accidentally give an `ImPlot` style var to an `ImGui` style var, and vice versa, but I'd rather have parity between the two APIs, and not have to remember that one is different from the other.

Overall, this well let us keep ImPlot well separated from ImGui and allow for more terse API. Thanks for the suggestion, Omar!

**Comment by epezent** [comment]
See what API function names changed here: https://github.com/epezent/implot/commit/be8c1ad679231ec26ddc36a31c512a351ada0b73

**Comment by ocornut** [comment]
Treat my feedback with a grain of salt (as I'm not yet a active user of this) but I think keeping `ImPlot::PlotBar()` is preferable to maintain a verb and a noun in the function names.

**Comment by epezent** [comment]
Fair point. I could lean either way. FWIW, [matlab](https://www.mathworks.com/help/matlab/ref/bar.html) and [matplotlib](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.bar.html) call in `bar`. 

@ozlb , @jpieper  @sergeyn, any thoughts on the matter? That is, the general style used for naming functions and such.

**Comment by jpieper** [comment]
My vote is for following consensus of other libraries.

**Comment by ozlb** [comment]
In imgui widgets `ImGui::PlotLines()` ; I understand that with ImPlot namespace it's a little bit redundant, but in this way it will seamless the namespace update.
To be honest, i will prefer update also `ImMarker` and `ImAxisFlags` with `ImPlotMarker` and `ImPlotAxisFlags`

**Comment by ocornut** [comment]
> My vote is for following consensus of other libraries.

Well but this is ambiguous because there's "consensus of plotting library" and "concensus of dear imgui ecosystem"

**Comment by epezent** [comment]
Not to be pedantic, but are these two really any different? 

``` cpp
if (ImGui::BeginMenu("menu")) {
    ImGui::MenuItem("item");
    ImGui::EndMenu();
}
```
```cpp
if (ImPlot::BeginPlot("plot")) {
    ImPlot::Bar("bar", data, 5);
    ImPlot::EndPlot();
}
```
`MenuItem` doesn't have a verb, and in general, many of the ImGui *elements* don't have a verb (e.g. `Text` isn't `RenderText` in the public API). @ocornut, any guidelines here? Understanding what we should model this after might be helpful.

I agree that making sure `ImPlot` is in all of our structs is a good call. I can do this now.

**Comment by ozlb** [comment]
Probably he wants to say that with `MenuItem()` you perfectly understand what will do but with `Bar()` not

**Comment by ozlb** [comment]
`BarGraph` "sounds" ok to me

**Comment by ocornut** [comment]
You are right they don't always have verb actually...
I don't have strict guidelines and in fact dear imgui itself has lots of inconsistencies (which I hope to fix in 2.0 overhaul).

To me having two functions `Plot` (for lines) and `Bar` feels very confusing, if anything to be consistent it should be `Lines` and `Bar`. My preference would still go for `PlotLines` and `PlotBar` as they provide less ambiguous information at a glance.

**Comment by epezent** [comment]
Ok thanks Omar! Like I said I don't have a strong preference here, but I lean towards being as "ImGui-like" as possible. So I'm willing to revert back to `PlotX` functions. 

In the case of plain `Plot`, it actually is used for lines and scatter depending on the formatting spec that is set. I think I may break this into `PlotLines` and `PlotPoints`. It's more clear and saves the user from setting a flag, anyhow.

**Comment by epezent** [comment]
The names of the plotting functions have been updated. Every function is now prefixed with `Plot`. In addition, I made the following changes:

`PlotLine` - Previously `Plot`. Intentionally kept singular. In a plotting context, a line is generally considered a single curve/trace even though graphically it is made of several line segments. `PlotLines` might suggest that multiple curves will be rendered.
`PlotScatter` - Previously scatter plots were made with `Plot` and setting `ImPlotStyleVar_LineWeight` to 0 and pushing an `ImPlotMarker`. That can still be done, but `PlotScatter` now provides a more direct path to plotting scatter plots -- no need to push anything.
`PlotBars/PlotBarsH` - made plural, since multiple bars will be plotted.
`PlotErrorBars` - ditto
`PlotPieChart` - same as before
`PlotDigital` - same as before
`PlotText` - same as before

Hopefully we won't have to do this again, and can maintain a consistent style from here forward. Thanks for the suggestions everyone!
