### ISSUE TITLE
Parallelizing the rendering stage

### ISSUE THREAD

**Issue by afalahat** [epezent/implot#345]
Is there any workaround for parallelizing rendering in `implot`? I am trying to accelerate rendering of more than 1,000,000 data points (`data.size()`>1,000,000). I get about 2 fps for rendering this large dataset.

```
// render data
for (int i = 0; i < data.size(); ++i) {
	ImU32 color      = ImGui::GetColorU32(data.open[i] > data.close[i] ? bearCol : bullCol);
	ImVec2 open_pos  = ImPlot::PlotToPixels(data.time[i] - half_width, data.open[i]);
	ImVec2 close_pos = ImPlot::PlotToPixels(data.time[i] + half_width, data.close[i]);
	draw_list->AddRectFilled(open_pos, close_pos, color);   
	ImVec2 low_pos   = ImPlot::PlotToPixels(data.time[i], data.low[i]);
	ImVec2 high_pos  = ImPlot::PlotToPixels(data.time[i], data.high[i]);
	draw_list->AddLine(low_pos,  high_pos , color, ImMax(1.0f, ImAbs(open_pos.x - close_pos.x)/10.0f));
}
```

The for-loop looks to be parallelizable and I tried using `tbb` to make it parallelize, but I had no success. 
```
// render data
tbb::parallel_for(0, data.size(), [&](int i) {
	ImU32 color = ImGui::GetColorU32(data.open[i] > data.close[i] ? bearCol : bullCol);
	ImVec2 open_pos = ImPlot::PlotToPixels(data.time[i] - half_width, data.open[i]);
	ImVec2 close_pos = ImPlot::PlotToPixels(data.time[i] + half_width, data.close[i]);
	draw_list->AddRectFilled(open_pos, close_pos, color);
	ImVec2 low_pos = ImPlot::PlotToPixels(data.time[i], data.low[i]);
	ImVec2 high_pos = ImPlot::PlotToPixels(data.time[i], data.high[i]);
	draw_list->AddLine(low_pos, high_pos, color, ImMax(1.0f, ImAbs(open_pos.x - close_pos.x) / 10.0f));
	}
);
```

**Comment by epezent** [comment]
Multithreading ImPlot and ImGui is going to be REALY difficult and probably not worth the effort. I don't advise pursuing this. You would be better off culling your data (do you _really_ need to render all 1,000,000 OHLC at once?), or using custom GPU acceleration (take a look at the `backends` branch).

**Comment by MichaelKv** [comment]
> Multithreading ImPlot and ImGui is going to be REALY difficult and probably
> not worth the effort. I don't advise pursuing this.
I use ImPlot to visualize hundreds of 10kHz channels and I do prepare data for ImPlot in parallel – each frame one window-size portion, I have no choice it will not work otherwise. The task is up to the limits for iCore5 and double processor workstation does not notice it at all. The design of the solution is extremely interesting and new for me and I am also happy the employer payed for the pleasure of the development though it was just a technological tool. And the ability of ImGui/ImPlot to render different parts of the screen (big and scrollable in my case) in parallel would be a big help indeed. But again, I do not complain – the development of a workaround was the fun.
The same arguments against parallelism and C++ exceptions I have already heard from the ImGui developer. To be honest he emphasized that ImGui is for the game development and that game developers do not use exceptions (I believe the multithreading part was not even mentioned) so I accepted his argumentation. But I would like to see a game that uses ImPlot…

**Comment by MichaelKv** [comment]
> Multithreading ImPlot and ImGui is going to be REALY difficult and probably
> not worth the effort. I don't advise pursuing this.

I use ImPlot to visualize hundreds of 10kHz channels and I do prepare data for ImPlot in parallel – each frame one window-size portion, I have no choice it will not work otherwise. The task is up to the limits for iCore5 and double processor workstation does not notice it at all. The design of the solution is extremely interesting and new for me and I am also happy the employer payed for the pleasure of the development though it was just a technological tool. And the ability of ImGui/ImPlot to render different parts of the screen (big and scrollable in my case) in parallel would be a big help indeed. But again, I do not complain – the development of a workaround was the fun.
The same arguments against parallelism and C++ exceptions I have already heard from the ImGui developer. To be honest he emphasized that ImGui is for the game development and that game developers do not use exceptions (I believe the multithreading part was not even mentioned) so I accepted his argumentation. But I would like to see a game that uses ImPlot…
Edit: tried to fix formatting.

**Comment by epezent** [comment]
Closing issue as we have no intentions of multirhreading ImPlot.
