### ISSUE TITLE
Is it possible to draw wave like ecg wave

### ISSUE THREAD

**Issue by masterchen** [epezent/implot#381]
It is a good project !

Is it possible to proivde a chart type which draw real time data wave line  like ecg wave ? 

like this : https://demo.scichart.com/javascript-vital-signs-ecg-medical-chart-example 

thanks you !

**Comment by dgm3333** [comment]
Did you look at the manual/demo? Theres already an example showing how to do that.

**Comment by epezent** [comment]
As already mentioned, see the second example under `Plots/Realtime Plots` in the demo:

![rt](https://user-images.githubusercontent.com/29577475/189492110-30d57930-36a9-44ca-b6f9-e6eaa4c73821.gif)

**Comment by masterchen** [comment]
the dawing method is not like the one show :  https://demo.scichart.com/javascript-vital-signs-ecg-medical-chart-example

javascript-vital-signs-ecg-medical-chart-example  shows that the history wave was "cleared" while drawing the new wave point.

**Comment by marcizhu** [comment]
You can do that yourself by just keeping the old data and overwriting it so that it looks like the example you provided.

ImPlot is an awesome library and it has an extensive feature set and customization options, but it just cannot cover all the possible use cases or visualization possibilities. Sometimes you just have to code it yourself.

**Comment by epezent** [comment]
This is actually shown in the official demo under "Realtime Plot" (both scrolling and rolling variants like OP requested).
