### ISSUE TITLE
Seeking Advice - `FitThisFrame` and narrow vertical graphs

### ISSUE THREAD

**Issue by JaapSuter** [epezent/implot#69]
Hello,

Looking for some advice here...

One of our potential uses for ImPlot involves rendering many graphs vertically next to each other, per the following screen shot:

![image](https://user-images.githubusercontent.com/44677/85426299-23fb8d00-b52f-11ea-9f46-b03f17e3c3da.png)

Which is a first-draft prototype mockup to reproduce functionality of a different application, which looks like this: 

![image](https://user-images.githubusercontent.com/44677/85426386-41305b80-b52f-11ea-886a-762396219e26.png)

Now, let me acknowledge that using ImPlot to draw graphs vertically (essentially swapping X and Y and hoping things will work) could be considered 'abusing' the library outside its intended use. But since it appears that (for the most part) ImPlot happy draws multiple Y values for unique X values, we figured it's worth exploring ImPlot for this use case.

We integrated the new `table` branch of ImGui and use the new table layout functionality to create the multiple column "tracks", each containing one graph. Thanks to ImGui we automatically get resizing, reordering, and hiding/showing of each track. Which is pretty cool.

So I became tentatively optimistic. 

The main issue where things currently fall down appears to be around double-click auto sizing (and the `FitThisFrame` functionality. For some reason, whenever the plot width shrinks below a certain size (like in the first screenshot above), the `FitThisFrame` logic appears to break down, and a double click on the graph no longer zooms to fit the entire graph.

I've stepped through ImPlot's code, and as far as I've been able to debug; all the logic around calculating the X- and Y-axis extents works as expected, as does the calculation of `Mx` in the `UpdateTransformCache`.

My hunch is that somewhere in the drawing code, `gp.PixelRange` is only willing to shrink to a certain point, beyond which it clamps to some kind of minimum graph width, and thus failing to fully fit the full extents of the graph's X-axis.

I'm not expecting you to debug this issue for us. Like I said, I recognize that ImPlot's primary purpose is to render traditional X-Y graphs with a horizontal layout (unfortunately that's not an option for us).

My questions are two-fold:

1. Specific to this issue -- without you spending time looking into this issue, do you happen to have any hunch as to why `FitThisFrame` might break down when a graph gets very narrow, and where I should look to debug this myself?

2. And more generally -- do you think using ImPlot is even a good idea here, or did we step so far outside of ImPlot's intended purpose, that we're better of writing our own bespoke graph/plot functionality? (FWIW, we already use ImPlot for several other panels in our application, that have traditional X-Y graphs, and we're very happy with it there).

Appreciate any thoughts, but I realize the open-endedness of this question, so feel free to ignore.

Thanks,

Jaap Suter

**Comment by epezent** [comment]
I have not tested ImGui Tables with ImPlot personally. It's neat to see that it's at least working to some degree! 

I can't think of any reason regular line plot shouldn't be rendered vertically like you've done. The only limitation that comes to mind right now is that PlotShaded (e.g. filled plots) are filled relative to a horizontal plane. But since you aren't doing that, it shouldn't be an issue.

> My hunch is that somewhere in the drawing code, gp.PixelRange is only willing to shrink to a certain point, beyond which it clamps to some kind of minimum graph width, and thus failing to fully fit the full extents of the graph's X-axis.

`gp.PixelRange` is constructed from `gp.BB_Plot` (i.e. the plot area bounding box) and current flags related to axis inversion. `gp.BB_Plot` is constructed using `gp.BB_Canvas` (the widget canvas/frame size) and padding values based on presence or absence of labels/titles. If this is in fact the issue, then my guess is that it's related to the construction of `gp.BB_Frame` and/or `gp.BB_Canvas`:

```cpp
gp.BB_Frame = ImRect(Window->DC.CursorPos, Window->DC.CursorPos + frame_size);
...
gp.BB_Canvas = ImRect(gp.BB_Frame.Min + Style.WindowPadding, gp.BB_Frame.Max - Style.WindowPadding);
```

Difficult to say without being able to test myself right now.

Regarding you questions:

1) No I can't. In fact, now that I think about it, I don't believe that `FitThisFrame` is even considering pixels at all. The general logic is to find the max and min x/y points in *plot space* and then change the axes ranges (in plot space) accordingly. Pixels and aspect ratio shouldn't be affecting this calculation. 
2) As I said above, I don't think you're doing anything outside of ImPlot's scope. We should be able to make this work for you.

I wonder if this is perhaps related to Tables capturing double click events before they can reach ImPlot. Can you:

1) Describe what actually happens when double clicking a table'd plot? Does it glitch, or just do nothing at all?
2) What happens when you do this outside of a Table context? E.g., does this still happen for plots that are sufficiently small even when they are created normally, outside of a Table?

**Comment by epezent** [comment]
Jaap, I can confirm this is an internal ImPlot issue. I'm investigating...

![zoom_glitch](https://user-images.githubusercontent.com/29577475/85490634-be8fb680-b597-11ea-8d01-005d8044925f.gif)

**Comment by epezent** [comment]
As you can see in the GIF, it seems to have fit Y but not X.

**Comment by epezent** [comment]
I've identified the culprit:

```cpp
const ImRect xAxisRegion_bb(gp.BB_Plot.Min + ImVec2(10, 0), ImVec2(gp.BB_Plot.Max.x, gp.BB_Frame.Max.y) - ImVec2(10, 0));
const bool   hov_x_axis_region = xAxisRegion_bb.Contains(IO.MousePos);
```

As you can see, there's a 10px buffer on the left and right side of the x-axis hover region. This was done so that the tick marks of the left and right Y axes can be double clicked, allowing Y axes to be independently fit in the absence of clickable labels. 

We could remove (reduce) this buffer zone, but that would make it impossible (difficult) to independently fit Y axes if there are no tick labels to double click on. We could also impose a minimum plot size (say 50px wide) so that there's always a generous clickable area in between the left/right buffers. The latter is probably the preferred path forward (for more reasons than this), but it's actually tricky to do since we'd need to precompute all the bounding areas before rendering the ImGui frame. Not impossible, but enough work that I don't have time to commit to it right now. Thoughts?

Does the Tables API provide a means to impose a minimum column width? That might be the quickest fix in your case.

**Comment by JaapSuter** [comment]
Per the feature list at: https://github.com/ocornut/imgui/issues/2957, it doesn't seem like the new table API supports minimum column width yet, but that it's a planned feature.

It's easy enough to ensure a minimum ourselves though. We'll simply multiply the minimum table width by the number of columns, and set that as the minimum width for the entire table. Granted, that would still allow people to resize an individual column to something smaller, but at a certain point we'd consider that user-error (while not ideal, we tolerate minor lack of polish in our application due to having chosen ImGui as our frontend. We don't ship externally, and the increase in UX development efficiency is well worth it)).

Come to think of it, I can simply detect when a user has dragged a column too small and thus broke the ImPlot area to a point where it's too narrow, and instead of plotting the graph, just draw the background in opaque red, as a warning that the user shouldn't do that.

Easy enough.

Thank you for looking into this!
