### ISSUE TITLE
Feature request - gantt chart / event chart

### ISSUE THREAD

**Issue by vinjn** [epezent/implot#86]
First, thanks for this awesome lib, I love it.
I am using implot to build a homebrew performance profiler / time series visualizer.
The current charts of implot can plot metrics well, and what I am missing is gantt chart, or event chart, as shown by the following screeshot, from https://github.com/Celtoys/Remotery:

![image](https://user-images.githubusercontent.com/558657/89701360-bc779080-d968-11ea-82db-40868dec7cf6.png)

Is is possible to have this kind of feature in implot, I believe it will benefit other users as well.

**Comment by epezent** [comment]
Hi @vinjn! This is somewhat outside of ImPlot's scope at the moment. Right now, we are focusing on plots that map well to 2D coordinate systems. 

Down the road, I do hope to support graphs like this, as well as flame graphs. These would likely require a separate plotting context and API instead of adapting them to the current `BeginPlot` / `EndPlot` mechanics.

In the meantime, you might find some usable code for this inside of [Tracy](https://github.com/wolfpld/tracy).

**Comment by vinjn** [comment]
Thanks

**Comment by Osmanyasal** [comment]
Hello, I also need a chart like that @vinjn did you find anything useful? I know It has been some time but wanted to ask anyway
thanks in advance.

**Comment by vinjn** [comment]
nope

**Comment by Osmanyasal** [comment]
I see,
For the newcomers; 
I'm going to implement chrome://tracing that you only need a json file with a specific format. It's offline logging meaining you can see the result after profiling is done but the gantt chart and usage is perfect
