### ISSUE TITLE
Gallery: Post Your Screenshots / Code Here (PART 1)

### ISSUE THREAD

**Issue by epezent** [epezent/implot#94]
Post your screenshots or custom code here and tell us about your project!

**Comment by epezent** [comment]
This is a tool I wrote for [Tasbi](http://evanpezent.com/hardware/tasbi/), a haptic wristband I built at Facebook Reality Lab and use for my PhD research. I'm using ImPlot to visualize and tune motor controllers, and calibrate sensor measurements. ImPlot works great with ImGui's docking branch!

![Tasbi](https://user-images.githubusercontent.com/29577475/77241246-5064dd80-6bbd-11ea-9a9f-28ab981c17de.png)

**Comment by epezent** [comment]
**Custom candlestick plots and tool tips:**

![candletool](https://user-images.githubusercontent.com/29577475/90851160-7b548880-e339-11ea-90b5-27b993421005.gif)

**ImPlot + ImGui Tables API:**

![tables](https://user-images.githubusercontent.com/29577475/90851187-8c04fe80-e339-11ea-8267-e6bfdc105686.gif)

Both of these have been added to `implot_demo.cpp`

**Comment by PeterJohnson** [comment]
Robot simulation GUI for FIRST robotics with multiple plots and drag and drop everything.


![drag and drop resized](https://user-images.githubusercontent.com/297126/91929143-9a84db80-ec92-11ea-80e1-3eea3ff8b890.gif)


https://github.com/wpilibsuite/allwpilib/pull/2653

**Comment by epezent** [comment]
@PeterJohnson , I'm curious how you got the linked axes working and if it is bidirectional. This is a feature I've wanted to implement.

**Comment by hoffstadt** [comment]
Some things DearPyGui users have made:

![fa08r61ae2i51](https://user-images.githubusercontent.com/39973752/92046481-3fadbb80-ed48-11ea-9b3b-9cc5ea6e3a4e.png)

![114vv9n3ask51](https://user-images.githubusercontent.com/39973752/92046084-c910be00-ed47-11ea-9a33-7a761eb7d356.jpg)

![91245835-0c4daa00-e714-11ea-8b3f-6ac01d6dbeb3](https://user-images.githubusercontent.com/39973752/92046379-ffe6d400-ed47-11ea-9a19-ab672fa9c26f.gif)
![89934768-b686e700-dbd6-11ea-9433-33c123f92a01](https://user-images.githubusercontent.com/39973752/92046423-1f7dfc80-ed48-11ea-9e91-5dc615e22bfd.png)

**Comment by PeterJohnson** [comment]
@epezent It is not bidirectional.  I just use SetNextPlotLimitsX() to force the X axis on the second plot to follow the first.  Bidirectional is a good idea.  I think how I would tackle that is to do the SetNextPlotLimitsX() on the other plots only when one of them is actively being dragged (there would be a 1-frame delay to updating the first plot when you dragged the second plot, but that's hardly noticeable).  However, to do this, I would need a method to detect when a plot is being dragged by the user.  Is that exposed in implot_internal.h?

**Comment by ozlb** [comment]
> @epezent It is not bidirectional. I just use SetNextPlotLimitsX() to force the X axis on the second plot to follow the first. Bidirectional is a good idea. I think how I would tackle that is to do the SetNextPlotLimitsX() on the other plots only when one of them is actively being dragged (there would be a 1-frame delay to updating the first plot when you dragged the second plot, but that's hardly noticeable). However, to do this, I would need a method to detect when a plot is being dragged by the user. Is that exposed in implot_internal.h?

I guess you will need as well PR https://github.com/epezent/implot/pull/98#bottom to disable “sync. slave” plot drag/drop if while clicking and dragging x axis you will travel over

**Comment by marcizhu** [comment]
Not sure if this one counts, but since I will be using this library to make an application for USB oscilloscopes, I've been doing some experiments where I plotted some (generated) signals into heatmaps in order to visually differentiate the random noise from the real signal. Here's the result:

<img width="1392" alt="img1" src="https://user-images.githubusercontent.com/6199781/98874475-9f2bf400-247a-11eb-9f6a-850c1db2fefc.png">
<img width="1392" alt="img2" src="https://user-images.githubusercontent.com/6199781/98874504-aa7f1f80-247a-11eb-8fda-e2555728c72d.png">
<img width="1392" alt="img3" src="https://user-images.githubusercontent.com/6199781/98874557-c682c100-247a-11eb-801a-82340750bb11.png">
<img width="1392" alt="img4" src="https://user-images.githubusercontent.com/6199781/98874572-cda9cf00-247a-11eb-81df-612d061a5b94.png">

I want to take this chance to thank @epezent and all the colaborators of this project for this amazing library. Sincerely, thank you all for your amazing work ❤️

**Comment by ozlb** [comment]
> Not sure if this one counts, but since I will be using this library to make an application for USB oscilloscopes, I've been doing some experiments where I plotted some (generated) signals into heatmaps in order to visually differentiate the random noise from the real signal. 

Does the sample increase the "weight" and time decrease it? It will be great to have a "light" version in the demo...

**Comment by marcizhu** [comment]
Indeed, every "hit" of the signal increases  the histogram value by 1. I also keep a variable with the maximum value on the histogram at every given moment so that the colors cover the maximum possible range, but using time would also be a solution if you want a "fade out" effect once the signal disappears.

I can post a snippet with the code tomorrow if you guys want :)

**Comment by marcizhu** [comment]
Indeed, every "hit" of the signal increases  the histogram value by 1. I also keep a variable with the maximum value on the histogram at every given moment so that the colors cover the maximum possible range, but using time would also be a solution if you want a "fade out" effect once the signal disappears.

I can post a snippet with the code tomorrow if you guys want :)

**Comment by epezent** [comment]
@marcizhu, that's cool! What's the performance like? I didn't really optimize heatmaps for high density display, but it'd be an easy fix if it's needed.

**Comment by epezent** [comment]
Also, @marcizhu, feel free to submit a PR adding a minimal example to the demo :)

**Comment by ozlb** [comment]
> Indeed, every "hit" of the signal increases the histogram value by 1. I also keep a variable with the maximum value on the histogram at every given moment so that the colors cover the maximum possible range, but using time would also be a solution if you want a "fade out" effect once the signal disappears.
> 
> I can post a snippet with the code tomorrow if you guys want :)

"Fade out" effect will help you not only when signals disappears but also when changes it's nature and a plot persistence factor to track signal modulations

**Comment by marcizhu** [comment]
> @marcizhu, that's cool! What's the performance like? I didn't really optimize heatmaps for high density display, but it'd be an easy fix if it's needed.

@epezent The performance is really great: the histogram has a size of 1024x256, and rendering it on a 1280x720 window (the screen is 2560x1600) on a MacBook Pro 2018 (so not the best GPU in the world) I get 60-80 frames consistently. If we take into account the fact that my code is just a quick & dirty demo and it is not optimized at all, I'd say the performance is more than acceptable :)

> Also, @marcizhu, feel free to submit a PR adding a minimal example to the demo :)

Great! I will be opening a PR in a few days. Right now I'm a bit busy with university and exams, but once time allows I will definitely open a PR :+1:

> "Fade out" effect will help you not only when signals disappears but generally when changes it's nature and a plot persistence factor will help you to track signal modulations

@ozlb That's totally true. I will try using time instead of just tracking the maximum value of the histogram and if the end result looks nice, I will add that to the demo instead :D

**Comment by ejyanezp** [comment]
Here is an application to display seismic data, thanks to the **implot** project.
![Screenshot from 2020-11-18 22-53-24](https://user-images.githubusercontent.com/7320357/99619217-f557e480-29f0-11eb-985f-abbd491ba657.png)

**Comment by ddovod** [comment]
My deep reinforcement learning playground, heavily using different kinds of plots. Big thanks to implot!
![rl_implot](https://user-images.githubusercontent.com/9406025/101241535-f5055c00-3707-11eb-93c6-438c9dc628ee.png)

**Comment by epezent** [comment]
A quick little toy I put together while working on some [DSP algorithms](https://github.com/epezent/etfe).

![filter_toy](https://user-images.githubusercontent.com/29577475/104275075-c9446700-5467-11eb-8d86-19c2688b1951.gif)

**Comment by elvissteinjr** [comment]
[Desktop+](https://github.com/elvissteinjr/DesktopPlus) is a tool to bring your desktop and more into SteamVR. A recent addition is the Performance Monitor. 
ImPlot is used here to render the frame time graphs.
![performance monitor](https://user-images.githubusercontent.com/12502199/104975436-e7c3d880-59fa-11eb-8c87-e4d037105138.jpg)
This is pretty basic as far as plotting goes, but I just wanted something to render neat looking graphs in Dear ImGui and ImPlot fit the bill nicely. Thanks for that.
